# Generated by Django 3.1.2 on 2020-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201112_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesection',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
