# Generated by Django 3.1.2 on 2020-11-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20201112_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
