# Generated by Django 3.1.2 on 2020-11-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20201112_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sections', to='content.page'),
        ),
    ]
