# Generated by Django 3.1.2 on 2020-11-13 16:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201113_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory'),
        ),
    ]
