# Generated by Django 3.1.2 on 2020-11-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201110_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_by',
            new_name='created_by',
        ),
    ]
