# Generated by Django 3.1.2 on 2020-11-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0008_auto_20201114_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infographic',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Main image'),
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='Infographic',
        ),
    ]
