# Generated by Django 3.1.2 on 2020-11-14 08:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201114_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
