# Generated by Django 3.1.2 on 2020-11-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201114_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostpage',
            old_name='image',
            new_name='cover_photo',
        ),
    ]
