# Generated by Django 3.1.2 on 2020-11-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201115_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
