# Generated by Django 3.1.2 on 2020-11-15 09:15

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpostpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='photo_credits',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('columns', wagtail.core.blocks.StreamBlock([('column_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html')), ('column_2_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html')), ('column_1_2', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html')), ('column_1_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_2', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html'))], form_classname='full'))]),
        ),
    ]
