# Generated by Django 3.1.2 on 2020-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201118_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'blog categories'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
