# Generated by Django 3.1.2 on 2020-11-19 07:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201118_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='related_pages',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock())], blank=True),
        ),
    ]
