# Generated by Django 3.1.2 on 2021-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210309_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
