# Generated by Django 3.1.2 on 2021-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210315_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Finnish)'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Finnish)'),
        ),
    ]
