# Generated by Django 3.1.2 on 2020-11-16 06:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header', wagtail.core.fields.RichTextField(max_length=500)),
                ('text', wagtail.core.fields.RichTextField()),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Background photo')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('text', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('columns', wagtail.core.blocks.StreamBlock([('column_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html')), ('column_2_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html')), ('column_1_2', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html')), ('column_1_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_2', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Common')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', template='blocks/columns.html'))], form_classname='full'))])),
                ('time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('excerpt', wagtail.core.fields.RichTextField(blank=True)),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
