# Generated by Django 3.1.2 on 2020-11-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
