# Generated by Django 3.1.2 on 2020-11-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventpage_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='text',
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.CharField(default='-', max_length=300),
            preserve_default=False,
        ),
    ]
