# Generated by Django 3.1.2 on 2020-11-13 22:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('pages', '0002_auto_20201113_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Background photo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full')), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.PageChooserBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text',
            field=wagtail.core.fields.RichTextField(default='-'),
            preserve_default=False,
        ),
    ]
