# Generated by Django 3.1.2 on 2020-11-14 06:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201113_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='team_members',
            field=wagtail.core.fields.StreamField([('team_member', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('bio', wagtail.core.blocks.RichTextBlock()), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False))]))], blank=True),
        ),
    ]
