# Generated by Django 3.1.2 on 2020-11-14 21:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201114_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='header',
            field=wagtail.core.fields.RichTextField(max_length=500),
        ),
    ]
