# Generated by Django 3.1.2 on 2020-11-15 13:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('pages', '0009_auto_20201114_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header', wagtail.core.fields.RichTextField(max_length=500)),
                ('text', wagtail.core.fields.RichTextField()),
                ('podcasts', wagtail.core.fields.StreamField([('podcast', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('url', wagtail.core.blocks.URLBlock())]))], blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Background photo')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='footer',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
