# Generated by Django 3.1.2 on 2020-11-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('pages', '0011_auto_20201116_0625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivitiesPage',
        ),
    ]
