# Generated by Django 3.1.2 on 2020-11-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('pages', '0012_delete_activitiespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolkitspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='toolkitspage',
            name='photo',
        ),
        migrations.DeleteModel(
            name='ToolkitPage',
        ),
        migrations.DeleteModel(
            name='ToolkitsPage',
        ),
    ]
