# Generated by Django 3.1.2 on 2021-03-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('pages', '0013_auto_20201116_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageRedirectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Suomi')], default='en', max_length=5, unique=True),
        ),
    ]
