# Generated by Django 3.1.2 on 2021-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210304_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Suomi')], default='en', max_length=5),
        ),
    ]
