# Generated by Django 3.1.2 on 2021-03-09 18:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('pages', '0015_auto_20210304_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_fi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.RichTextBlock(form_classname='full')), ('text', wagtail.core.blocks.RichTextBlock()), ('text_fi', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.PageChooserBlock()), ('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_text_fi', wagtail.core.blocks.CharBlock(required=False))]))], blank=True),
        ),
        migrations.DeleteModel(
            name='LanguageRedirectionPage',
        ),
    ]
