# Generated by Django 3.1.2 on 2021-03-09 19:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210309_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='footer_fi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Footer (Finnish)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_fi',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Header (Finnish)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_fi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Text (Finnish)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Footer (English)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='header',
            field=wagtail.core.fields.RichTextField(max_length=500, verbose_name='Header (English)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_members',
            field=wagtail.core.fields.StreamField([('team_member', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock(label='Title (English)')), ('title_fi', wagtail.core.blocks.CharBlock(label='Title (Finnish)', required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('bio', wagtail.core.blocks.RichTextBlock(label='Bio (English)')), ('bio_fi', wagtail.core.blocks.RichTextBlock(label='Bio (Finnish)', required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='text',
            field=wagtail.core.fields.RichTextField(verbose_name='Text (English)'),
        ),
    ]
