# Generated by Django 3.1.2 on 2021-03-09 19:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210309_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastspage',
            name='header_fi',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Header (Finnish)'),
        ),
        migrations.AddField(
            model_name='podcastspage',
            name='text_fi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Text (Finnish)'),
        ),
        migrations.AlterField(
            model_name='podcastspage',
            name='header',
            field=wagtail.core.fields.RichTextField(max_length=500, verbose_name='Header (English)'),
        ),
        migrations.AlterField(
            model_name='podcastspage',
            name='podcasts',
            field=wagtail.core.fields.StreamField([('podcast', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title (English)')), ('title_fi', wagtail.core.blocks.CharBlock(label='Title (Finnish)', required=False)), ('thumbnail', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(label='Description (English', required=False)), ('description_fi', wagtail.core.blocks.RichTextBlock(label='Description (Finnish)', required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='podcastspage',
            name='text',
            field=wagtail.core.fields.RichTextField(verbose_name='Text (English)'),
        ),
    ]
