# Generated by Django 3.1.2 on 2021-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210309_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Finnish)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Finnish)'),
        ),
        migrations.AddField(
            model_name='podcastspage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Finnish)'),
        ),
    ]
