# Generated by Django 3.1.2 on 2020-11-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightoutput',
            name='insight',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.insight'),
            preserve_default=False,
        ),
    ]
