# Generated by Django 3.1.2 on 2020-10-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('o', 'Organizational'), ('c', 'Creative'), ('s', 'Social'), ('p', 'Polarity')], max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#ccc', max_length=7)),
                ('directional', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_own', models.BooleanField(default=True)),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'Less than 5 employees'), (5, '5 - 9 employees'), (10, '10 or more employees')], default=3)),
                ('graph', models.JSONField(blank=True, null=True)),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.purpose')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.sector')),
            ],
        ),
    ]
