# Generated by Django 3.1.2 on 2020-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationtype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='relationtype',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Less than 5 employees'), (2, '5 - 9 employees'), (3, '10 or more employees')], default=3),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='color',
            field=models.CharField(blank=True, default='#ccc', max_length=7, null=True),
        ),
    ]
