# Generated by Django 3.1.2 on 2020-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201028_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationtype',
            options={'ordering': ('group', 'order')},
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='relationtype',
            unique_together={('group', 'order')},
        ),
    ]
