# Generated by Django 3.1.2 on 2020-10-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201028_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='is_own',
            field=models.BooleanField(default=True, help_text="Uncheck the box if you are mapping an other organization's network", verbose_name='This is my own organization'),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the organization'),
        ),
        migrations.AlterField(
            model_name='map',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.purpose', verbose_name='Your primary purpose of using this tool'),
        ),
        migrations.AlterField(
            model_name='map',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.sector', verbose_name='The sector of the organization'),
        ),
        migrations.AlterField(
            model_name='map',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Less than 5 employees'), (2, '5 - 9 employees'), (3, '10 or more employees')], default=3, verbose_name='Size of the organization'),
        ),
    ]
