# Generated by Django 3.1.2 on 2020-11-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolkitspage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='toolkitspage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='toolkitspage',
            name='text',
        ),
        migrations.AddField(
            model_name='toolkitpage',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
