# Generated by Django 3.1.2 on 2020-11-16 09:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('toolkits', '0002_auto_20201116_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolkitpage',
            name='pinned',
        ),
        migrations.AddField(
            model_name='toolkitspage',
            name='cover_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='toolkitpage',
            name='tools',
            field=wagtail.core.fields.StreamField([('tool', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))])), ('doc', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('file', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))]),
        ),
    ]
