# Generated by Django 3.1.2 on 2020-11-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkits', '0003_auto_20201116_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolkitpage',
            old_name='cover_photo',
            new_name='image',
        ),
    ]
