# Generated by Django 3.1.2 on 2020-11-16 09:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('toolkits', '0004_auto_20201116_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkitpage',
            name='tools',
            field=wagtail.core.fields.StreamField([('tool', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))])), ('doc', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('file', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))]),
        ),
    ]
