# Generated by Django 3.1.2 on 2020-11-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkits', '0006_auto_20201116_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolkitpage',
            old_name='image',
            new_name='background_image',
        ),
    ]
