# Generated by Django 3.1.2 on 2020-11-20 12:28

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toolkits', '0008_auto_20201120_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkitspage',
            name='header',
            field=wagtail.core.fields.RichTextField(default='Toolkits', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolkitspage',
            name='text',
            field=wagtail.core.fields.RichTextField(default=' '),
            preserve_default=False,
        ),
    ]
