# Generated by Django 3.1.2 on 2020-11-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StakeholderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_no', models.PositiveSmallIntegerField()),
                ('question', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('batch_no', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the organization')),
                ('is_own', models.BooleanField(default=True, help_text="Uncheck the box if you are mapping another organization's network", verbose_name='This is my own organization')),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'Less than 5 employees'), (2, '5 - 9 employees'), (3, '10 or more employees')], default=3, verbose_name='Size of the organization')),
                ('stakeholders', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapper.purpose', verbose_name='Your primary purpose of using this tool')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.sector', verbose_name='The sector of the organization')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapper.workshop')),
            ],
        ),
    ]
