# Generated by Django 3.1.2 on 2020-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('page_no',),
            },
        ),
        migrations.AlterModelOptions(
            name='stakeholdertype',
            options={'ordering': ('batch_no', 'order'), 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
    ]
