# Generated by Django 3.1.2 on 2020-11-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='map',
            name='terms_accepted',
        ),
    ]
