# Generated by Django 3.1.2 on 2020-11-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20201126_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='page_no',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
