# Generated by Django 3.1.2 on 2020-11-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20201107_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='stakeholders',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
