# Generated by Django 3.1.2 on 2020-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20201126_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='page_no',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
