# Generated by Django 3.1.2 on 2020-11-09 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_map_stakeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
