# Generated by Django 3.1.2 on 2020-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_auto_20201110_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_no', models.PositiveSmallIntegerField()),
                ('question', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='RelationType',
        ),
    ]
