# Generated by Django 3.1.2 on 2020-11-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0006_auto_20201111_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeholdertype',
            old_name='group_no',
            new_name='batch_no',
        ),
    ]
