# Generated by Django 3.1.2 on 2020-11-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0006_auto_20201128_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='own_parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
