# Generated by Django 3.1.2 on 2020-11-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_map_own_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Your primary purpose of using this tool'),
        ),
    ]
