# Generated by Django 3.1.2 on 2020-11-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_auto_20201111_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderTypeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stakeholdertype',
            name='batch_no',
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapper.stakeholdertypebatch'),
        ),
    ]
