# Generated by Django 3.1.2 on 2020-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0008_auto_20201111_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholdertype',
            name='batch',
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='batch_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StakeholderTypeBatch',
        ),
    ]
