# Generated by Django 3.1.2 on 2021-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0009_auto_20201214_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='description_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Finnish)'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='title_fi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title (Finnish)'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Finnish)'),
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='description_fi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description (Finnish)'),
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='name_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Finnish)'),
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='question_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Question (Finnish)'),
        ),
    ]
