# Generated by Django 3.1.2 on 2020-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0009_auto_20201111_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholdertype',
            options={'ordering': ('batch_no', 'order')},
        ),
        migrations.AlterField(
            model_name='stakeholdertype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
