# Generated by Django 3.1.2 on 2021-03-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0010_auto_20210304_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholdertype',
            name='name_fi',
        ),
    ]
